name: Publish documentation to GH-Pages
on: push

jobs:
  build:
    name: Generate HTML docs

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y latexmk texlive-fonts-recommended texlive-latex-extra texlive-pictures
    - name: Ensure proper style
      run: python -m hatch run lint:style
    - name: Generate docs
      shell: bash
      run: |
        # generate all formats we want to distribute
        python -m hatch run docs:build html
        python -m hatch run docs:build pdf
        python -m hatch run docs:build epub

        # create empty dir in HTML docs site
        mkdir -p docs/_build/html/files/
        # move other formats into the HTML docs
        mv \
          docs/_build/pdf/sphinxcontrib-relativeinclude.pdf \
          docs/_build/epub/sphinxcontrib-relativeinclude.epub \
          docs/_build/html/files/
        # pack everything up for further distribution
        tar \
          --dereference --hard-dereference \
          --directory docs/_build/html \
          -cvf "$RUNNER_TEMP/artifact.tar" \
          .
    - name: Upload docs
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: ${{ runner.temp }}/artifact.tar
        retention-days: 1
        if-no-files-found: error

  deploy:
    name: Publish docs to GH-Pages

    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # only publish new docs on tag pushes
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
